on: workflow_dispatch

jobs:
  build:
    name: build
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        target: [armv7-linux-androideabi, aarch64-linux-android, i686-linux-android, x86_64-linux-android]
        include:
          - arch: arm64-v8a
            target: aarch64-linux-android
          - arch: armeabi-v7a
            target: armv7-linux-androideabi
          - arch: x86
            target: i686-linux-android
          - arch: x86_64
            target: x86_64-linux-android

    steps:
      - uses: actions/checkout@v4
      - name: Setup NDK
        run: |
          N="android-ndk-r27b"
          wget -nv https://dl.google.com/android/repository/${N}-linux.zip
          unzip -qo ${N}-linux.zip
          chmod -R 777 ./${N}
          export NDK_HOME="$(pwd)/${N}"
          cargo install cargo-ndk
          mkdir -p output

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
          components: rust-src
          target: ${{ matrix.target }}

      - name: Build
        run: |
          cargo ndk -t ${{ matrix.arch }} -p 24 -- build --release -j $(nproc)
          mv -f ./target/${{ matrix.target }}/release/cmpr ./output/cmpr-${{ matrix.arch }}

      - id: date
        run: echo ::set-output name=date::$(date +'%Y%m%d')

      - name: Upload
        uses: svenstaro/upload-release-action@v2
        with:
          file: ./output/*
          release_name: cmpr
          tag: ${{ steps.date.outputs.date }}
          overwrite: true
          file_glob: true
